# .graphclientrc.yml
sources:
  - name: tidv
    handler:
      graphql:
        endpoint: https://{context.indexer_url:gateway.thegraph.com/api/408304b8f418be03f0c0aa1bcc4282fe/subgraphs/id/FDD65maya4xVfPnCjSgDRBz6UBWKAcmGtgY6BmUueJCg}
        chainName: { context.chainName }

additionalTypeDefs: |
  extend type _Meta_ {
    chainName: String!
    subgraphUrl: String!
  }

additionalResolvers:
  - ./graph/resolvers.ts

documents:
  - ./queries/get-subgraph-status.graphql