# .graphclientrc.yml
sources:
  - name: tidv
    handler:
      graphql:
        endpoint: https://{context.indexer_url:api.thegraph.com/subgraphs/name/airswap/airswap}
        chainName: { context.chainName }

additionalTypeDefs: |
  extend type _Meta_ {
    chainName: String!
    subgraphUrl: String!
  }

additionalResolvers:
  - ./queries/resolvers.ts

documents:
  - ./queries/get-subgraph-status.graphql