import { ReactNode } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import { Button } from "./common/Input";

export const Layout = (props: { children: ReactNode }) => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div>{props.children}</div>
      </main>
      <Navigation />
    </>
  );
};

export const Navigation = () => {
  return (
    <nav className="btm-nav">
      <Link href="/">Home </Link>
      <Link href="/relays">Relays</Link>
      <Link href="/identities">Identities</Link>
    </nav>
  );
};
