import { ReactNode } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import { useNostrRelays } from "../hooks/useNostrRelays";
import { Button } from "./common/Input";

export const Layout = (props: { children: ReactNode }) => {
  const router = useRouter();
  const { relayStatus } = useNostrRelays();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/** <Sidebar /> */}
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/** <Header /> */}
        {router.pathname !== "/" && (
          <Button
            onClick={() => {
              router.back();
            }}
            className="rounded bg-[#ff00ff] py-2 px-4 font-bold text-white"
          >
            Back
          </Button>
        )}
        {router.pathname === "/" && (
          <Link href="/relays">
            <Button className="rounded bg-[#ff00ff] py-2 px-4 font-bold text-white">
              Relays
            </Button>
          </Link>
        )}
        <div>{props.children}</div>
      </main>
    </>
  );
};
