import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { Relay } from "../components/Relay";
import { useAppStore } from "../store";
import NoSSR from "../components/NoSSR";
import { Events } from "../components/Events";
import { AddRelay } from "../components/AddRelay";
import { Identities } from "../components/Identities";

const Home: NextPage = () => {
  const nostrRelays = useAppStore.use.nostrRelays().slice(0, 10);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-4xl font-bold text-white">
          Welcome to <a>Blabla</a>!
        </h1>
        <NoSSR>
          <div className="flex max-w-prose flex-wrap items-center justify-center gap-4">
            {nostrRelays.map((relayUrl, index) => (
              <Relay key={relayUrl.id} relay={relayUrl} index={index} />
            ))}
            <AddRelay />
            <Identities />
            <Events />
          </div>
        </NoSSR>
      </main>
    </>
  );
};

export default Home;
